### ISSUE TITLE
dagger docker-compose 安装遇到的一些问题

### ISSUE THREAD

**Issue by Cail423** [CloudmindsRobot/dagger#14]
①dagger-mysql 容器无法启动
   解决办法: 在docker服务器上，useradd -u 999 mysql， chonw -R mysql  /usr/local/src/dagger/dagger/production/config
②dagger-backend 容器无法与loki服务交互
  解决办法：修改 docker-compose.yaml dagger-backend 容器内挂载的 ../backend/dagger.ini 修改为./config/dagger.ini

**Comment by chenshunliang** [comment]
docker-compose 文件已经更改 感谢提出问题

**Comment by chenshunliang** [comment]
docker-compose 文件已经更改 感谢提出问题 @Cail423

**Comment by chenshunliang** [comment]
我们将mysql初始化做到了镜像初始化中去了（基于mysql:8.0），避免了路径和权限的问题
