### ISSUE TITLE
希望在Dagger内增加日志输出的自定义行数

### ISSUE THREAD

**Issue by CloudXiaobai** [CloudmindsRobot/dagger#6]
### feature支持

**根据群友反馈，希望在Dagger内增加日志输出的自定义行数**
![image](https://user-images.githubusercontent.com/2688646/98239501-04777500-1fa3-11eb-8e1d-116d39f46dd0.png)
![image](https://user-images.githubusercontent.com/2688646/98239223-9468ef00-1fa2-11eb-96ed-433d67764587.png)

**grafana7.3版本之后的版本也逐渐意识到这个问题，希望dagger跟进**
![image](https://user-images.githubusercontent.com/2688646/98239416-e6aa1000-1fa2-11eb-91c7-0cc73b013e3b.png)

**Comment by chenshunliang** [comment]
我们将在下一个小版本更新中支持该功能

**Comment by chenshunliang** [comment]
new version [https://github.com/CloudmindsRobot/dagger/releases/tag/0.1.2-beta](url)

**Comment by chenshunliang** [comment]
https://github.com/CloudmindsRobot/dagger/releases/tag/0.1.2-beta。  0.1.2-beta supported
