### ISSUE TITLE
OpenLdap支持

### ISSUE THREAD

**Issue by CloudXiaobai** [CloudmindsRobot/dagger#7]
### feature支持

根据群友反馈，希望在Dagger内增加openldap账号管理支持
![image](https://user-images.githubusercontent.com/2688646/100174591-ad145700-2f07-11eb-9d88-3ce493379674.png)

**Comment by chenshunliang** [comment]
开放对ldap的支持，详细请参阅dagger.ini中配置，beta版本为0.1.3-beta
